language: python
python:
  - "3.6"

cache:
  directories:
  - "/opt/sharedlibs"
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLUSTER_NAME=standard-cluster-1
  - CLUSTER_PROJECT=gcp-home-dev
  - CLUSTER_ZONE=europe-west3-a
  - DEPLOYMENT_NAME=img-slider
  - IMAGE_NGINX=gcr.io/gcp-home-dev/salt-nginx:a46e3c3c1cffd151c62457634a0a7a45ee915990
  - IMAGE_SLIDER=gcr.io/gcp-home-dev/flask-slider:62e8ae8dfd9f6646427c6466f84a3fc931aa9236
  - MAX_REPLICAS=1
  - MIN_REPLICAS=1
  - NAMESPACE=img-slider
  - SALT_API_USERNAME=saltdeployer
  - USERNAME=testuser
  - IMAGE_SLIDER_FQDN=images.th0r.de
  - SALT_API_URL=https://salt.th0r.de
  # envs: PASSWORD SALT_API_PASSWORD
  - secure: eLlfO+5F2fTX5tMHlEamkYgtWhkGGtEuSsoc5cCC0vxL0ACt3XbH0qaZv9HpqT+OQwP0+UMvRm4br5WxpQ4QCkG/5MVKne8HG0hl1+FZJwEptaJRBcoJLAT2N4qh9jn5HnRPb9gwMHTaJxplbf8r06uLe7uEXwR58gVCkh43p36eKPXCCQjotmsvRnLa35n3cLfa1h1uYFKt4AhSE9vCcpLRb8CP97GvZztcQnF4OKqa4ikWgE0TSmO1hxP+QLHol8x+Px/6I6edyDXLUE5lp0LAo0822VZjZqFgQHH78IETZkJaaeeWtspwMyJTQxkvSHJob/jVkh2svp58mthFVplouGW0JH6ulfz2+QvLrlDF+hNt5DBE/AYY4CXISqH3ejP8ocuA9+i1fqd2IhMgkJDYsnWy1NxeKuqkAZftsVJOsF/FR8ELmOvKMQUncOXMkXapgL4jCRh3GUXXLF3gFhQ/GPR8YD9rjT+hu2u/6SnNhz7Nxuk7LrOWqiRyKIXY3XINIlnQfe0JqcESd3xndmQkP+ztB9GPfRXvRsUm1PlvKmixZsCKba9ggWUqjsjxesESO6ETNnLcsOPIs7keGECbVCmth9aiFcVzwWXFfioNbdUQb40g4rCWTZlTd7WZYWXTQMn/yL7hUStWTNEGFO38iMLKAT+OqX2EPK0JAqU=

before_install:
- openssl aes-256-cbc -K $encrypted_445d4b2a7a9a_key -iv $encrypted_445d4b2a7a9a_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- sudo apt-get install apt-transport-https git
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
- echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee
  -a /etc/apt/sources.list.d/google-cloud-sdk.list
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update
- mkdir -p /opt/sharedlibs/
- "/bin/bash -c 'if ls /opt/sharedlibs/.git ; then git -C /opt/sharedlibs/ pull; else
  git clone https://github.com/Cookiiiies/sharedlibs.git /opt/sharedlibs/; fi'"
install:
- pip install -r pip/requirements.txt
- sudo apt-get install google-cloud-sdk kubectl
- kubectl version --client
- gcloud --version
- mkdir -p ${HOME}/k8s_descriptions
- gcloud auth activate-service-account --key-file image-slider-deployment.priv
- gcloud container clusters get-credentials ${CLUSTER_NAME} --zone ${CLUSTER_ZONE}
  --project ${CLUSTER_PROJECT}
before_script:
- export BUCKET_CREDENTIAL=$(base64 -w0 image-slider.priv)
script:
- python2 /opt/sharedlibs/python/deploy_k8s.py
